### ISSUE TITLE
More Jumps (LABELS) inside AMAL

### ISSUE THREAD

**Issue by AmitenTV** [AmiDARK/AmosProfessionalUnity-Official-Releases#10]
Hello,

Original Amos Professional let us to assign up to 25 Jumps (A-Z) inside Amal Scripts , if I dont remember bad.
But some times 25 Jumps aren´t  enough for our scripts ...

Any idea if is possible to increase the numbers of Jumps (Labels) inside Amal?¿

Thank you!

**Comment by AmiDARK** [comment]
Duplicate : https://github.com/AmiDARK/AmosProfessionalUnity-Official-Releases/issues/11
