### ISSUE TITLE
Cannot return to editor after Copper Off/Copper On pair (on AGA only)

### ISSUE THREAD

**Issue by alpyre** [AmiDARK/AmosProfessionalUnity-Official-Releases#7]
Copper On does not seem to work properly on AGA.

**To reproduce:**
```
Copper Off
Wait Key
Copper On
End
```

Works as expected on ECS.

**Comment by AmiDARK** [comment]
Bug confirmed (Reproduced).

**Comment by AmiDARK** [comment]
Fixed download latest build for fix
