### ISSUE TITLE
LOAD IFF Auto-Screen Open

### ISSUE THREAD

**Issue by HoraceAndTheSpider** [AmiDARK/AmosProfessionalUnity-Official-Releases#8]
If a screen is not yet opened, and LOAD IFF "FILE.iFF" is used without a screen number, it should open a screen of the correct size/resolution - currently it returns and error saying the screen is not the right size/depth as "the one at line X" (but X is the line number for the LOAD iFF)

**Comment by AmiDARK** [comment]
Exactly, when you start, screen 0 is automatically created and set as "current screen". If you close it and use "Load Iff" without providing any ID for a screen to use, it will fail with an error message "Screen not opened". I have just checked now.

I close this ticket.
